Hackfest/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('healthcare/', include('healthcare.urls')),
    path('doctor/', include('doctor.urls')),
]

doctor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.doctorHome),
    path('/patient-list/', views.patientList),
    path('/patient-list/patient/<int:patientId>', views.patientRecord,name='patientDiagnosis'),
    path('/viewPrescription/<int:prescriptionId>', views.viewPrescription, name="viewPrescription"),
    path('/diagnosis/<int:patientId>', views.diagnosis),
    path('/medication/<int:prescriptionId>', views.medication),
    path('/searchpage/', views.searchPatient, name='searchlist'),
    path('/medicineFile/<int:prescriptionId>', views.medicineFile, name='medicineFile'),
    path('/laboratoryTest/<int:prescriptionId>', views.laboratoryTest, name='laboratoryTest'),
    path('/viewMedicine/<int:medicineId>/<int:prescriptionId>',views.viewMedicine, name='viewMedicine'),

    path('add_medicine/<int:patient_id>/', views.add_medicine, name='add_medicine'),
    path('patient/<int:patient_id>/medicine/', views.patient_medicine, name='patient_medicine'),
     path('<int:patient_id>/update_medicine/<int:medicine_id>/', views.update_medicine, name='update_medicine'),

    path('add_diagnosis/<int:patient_id>/', views.add_diagnosis, name='add_diagnosis'),
    path('view_diagnosis/<int:patient_id>/', views.view_diagnosis, name='view_diagnosis'),
    path('patient/<int:patient_id>/update_diagnosis/', views.update_diagnosis, name='update_diagnosis'),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homePage, name=''),
    path('aboutUs', views.aboutUs, name='aboutUs'),
    path('registrationNo', views.registrationNo, name='registrationNo'),
    path('registrationNoSubmit', views.registrationNoSubmit, name='registrationNoSubmit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password=None, **extra_fields):
        """
        Create and save a user with the given email and password.
        """

        if not email:
            raise ValueError("The 'email' must be set")
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)  # Set and hash the password
        user.save(using=self._db)  # Ensure to save using the database that the manager is bound to
        
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """

        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(("Superuser must have is_superuser=True."))
        
        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    USER_TYPES = (
        ('admin', 'admin'),
        ('patient', 'patient'),
        ('doctor', 'Doctor'),
    )
    username = models.CharField(max_length=50)
    user_type = models.CharField(max_length=10, choices=USER_TYPES)
    full_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    objects = CustomUserManager()

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.core.checks import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, response
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib import messages
from .models import *
from django.contrib.auth import authenticate
from .models import Prescription, Medicine, Diagnosis,MedicalDevice,LaboratoryTest,MedicineDirection,MedicineDirPrescriptionMap
from healthcare.models import Patient, PatientRecord
from accounts.middleware import  doctor_middleware , both_middleware,doctordata_middleware, doctordata1_middleware
from django.db import transaction

from django.http import FileResponse
import io
# from reportlab.pdfgen import canvas
# from reportlab.lib.units import inch
# from reportlab.lib.pagesizes import letter

def medicineFile(request, prescriptionId):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize= letter, bottomup= 0)
    textob= c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 16)
    p=("Patient Name-")
    textob.textLine(p)
    prescription = Prescription.objects.get(pk=prescriptionId)
    patient = Patient.objects.get(pk=prescription.patientId.id)
    diagnosis = Diagnosis.objects.get(pk=prescription.diagnosisId.id)
    medicinDirMap = MedicineDirPrescriptionMap.objects.filter(prescriptionId=prescription)
    textob.textLine(patient.name)
    q=("Diagnosis Name-")
    textob.textLine(q)
    textob.textLine(diagnosis.diagnosisName)
    r=("----------------------------------------------------------")
    textob.textLine(r)
    t=("[MEDICINES]")
    textob.textLine(t)
    if len(medicinDirMap) != 0:
            print('in if')
            medsDirList = []
            for entry in medicinDirMap:
                medsDir = MedicineDirection.objects.filter(pk=entry.medicineDirectionId.id).first()
                medsName = Medicine.objects.filter(pk=medsDir.medicineId.id).first()
                medsDirList.append({
                    'medsDir':medsDir,
                    'medsName':medsName
                })
            lines = []
            for meds in medsDirList:
                lines.append("Name-")
                lines.append(meds['medsName'].name)
                lines.append("Dose Unit-")
                lines.append(meds['medsDir'].doseUnit)
                lines.append("Duration-")
                lines.append(meds['medsDir'].duration)
                lines.append("Number Of Times-")
                lines.append(meds['medsDir'].doseTiming)
                lines.append("Instruction-")
                lines.append(meds['medsDir'].additionalInstruction)
                lines.append("Reason-")
                lines.append(meds['medsDir'].reason)
                lines.append("----------------------------------------------------------")
            
            for line in lines:
                textob.textLine(line)
    c.drawText(textob) 
    c.showPage() 
    c.save()  
    buf.seek(0)
    return FileResponse(buf, as_attachment=True, filename='medicine.pdf')

@both_middleware
def searchPatient(request):
    try:
        print(request.session['role'])
        if request.session['role']!= "Doctor" and request.session['role']!="Nurse":
            return render(request, 'index.html', {'messages': "You Are Not Authenticated"})
        if request.method == 'POST':
            searched = request.POST['searched']
            data = Patient.objects.filter(name__contains=searched)
            return render(request, "patientlist.html", {'data':data})   
    
    except Exception as e:
        messages.add_message(request, messages.ERROR, "Please Add Valid Details !")
        return render(request, "viewPatientRecord.html")

@both_middleware
def doctorHome(request):
    try:
        if request.session['role']!= "Doctor" and request.session['role']!="Nurse":
            messages.add_message(request, messages.ERROR, "Please Add Valid Details !")
            return render(request, 'index.html')
        return render(request, "doctor.html", {}) 
    except Exception as e:
        messages.add_message(request, messages.ERROR, "Please Add Valid Details !")
        return render(request, "index.html")

# Patient List
@both_middleware
def patientList(request):
    try:
        if request.session['role']!= "Doctor" and request.session['role']!="Nurse":
            messages.add_message(request, messages.ERROR, "Please Add Valid Details !")

            return render(request, 'index.html')
        data_pagin = Patient.objects.all().order_by('-createdDate')
        paginator = Paginator(data_pagin, 10)
        page_number = request.GET.get('page')
        data = paginator.get_page(page_number)
        return render(request, "patientlist.html", {'data':data})     
    except Exception as e:
        print(e)
        messages.add_message(request, messages.ERROR, "Please Add Valid Details !")
        return render(request, "viewPatientRecord.html")

# Patient Detail
def patientRecord(request, patientId):
    try:
        patientDetails = Patient.objects.get(pk=patientId)
        his = PatientRecord.objects.filter(patientId=patientDetails)
        if(len(his)!=0):
            history=his.first()
            allPrescription = Prescription.objects.filter(patientId=patientDetails)
            prescriptionListData = []
            for prep in allPrescription:
                diagnosis = Diagnosis.objects.get(pk=prep.diagnosisId.id)
                prescriptionListData.append({
                    'diagnosisCreatedDate': diagnosis.createdDate,
                    'diagnosisName': diagnosis.diagnosisName,
                    'prescriptionId':prep.id
                })
            return render(request, "viewPatientRecord.html", {'history':history, 'details':patientDetails,'prescriptionList':prescriptionListData}) 
        else:
            return render(request, "viewPatientRecord.html", {'noRecord':True, 'details':patientDetails})
    except Exception as e:
        print(e)
        messages.add_message(request, messages.ERROR, "Please Add Valid Details !")
        return redirect('/')

# See Prescription
def viewMedicine(request,medicineId,prescriptionId):
    try:
        medicineDetails = Medicine.objects.get(pk=medicineId)
        return render(request,'viewMedicine.html',{'medicineDetails': medicineDetails,'prescriptionId':prescriptionId})
    except Exception as e:
        print(e)
        return redirect('viewPrescription',prescriptionId)

def viewPrescription(request, prescriptionId):
    try:
        prescription = Prescription.objects.get(pk=prescriptionId)
        patient = Patient.objects.get(pk=prescription.patientId.id)
        diagnosis = Diagnosis.objects.get(pk=prescription.diagnosisId.id)
        medicalDevice = MedicalDevice.objects.get(pk=prescription.medicalDevice.id)
        laboratoryTest = LabTestPrescriptionMap.objects.filter(prescriptionId=prescription)
        tests=[]
        if(len(laboratoryTest)>0):
            for lab in laboratoryTest:
                test = LaboratoryTest.objects.get(pk=lab.laboratoryTestId.id)
                tests.append(test)
        medicinDirMap = MedicineDirPrescriptionMap.objects.filter(prescriptionId=prescription)
        medsDirList = []
        if len(medicinDirMap) != 0:
            for entry in medicinDirMap:
                medsDir = MedicineDirection.objects.filter(pk=entry.medicineDirectionId.id).first()
                medsName = Medicine.objects.filter(pk=medsDir.medicineId.id).first()
                medsDirList.append({
                    'medsDir':medsDir,
                    'medsName':medsName
                })
                print(medsDirList)
        data = {
            'prescriptionId':prescriptionId,
            'patient':patient,
            'diagnosis':diagnosis,
            'medicalDevice':medicalDevice,
            'laboratoryTest':tests,
            'medsDirList':medsDirList
        }
        return render(request, "diagnosisDescription.html",{'data':data})
       
    except Exception as e:
        print(e)
        messages.add_message(request, messages.ERROR, "Something went wrong!")

        return render('/')   

@doctordata1_middleware
def laboratoryTest(request,prescriptionId):
    try:
        if request.method == 'POST':
            testName = request.POST.get('testName',None)
            testBodySite = request.POST.get('testBodySite',None)
            testUse = request.POST.get('testUse',None)
            testDescription =  request.POST.get('testDescription',None)
            testSpecimen =  request.POST.get('testSpecimen',None)
            with transaction.atomic():
                laboratoryTestData = LaboratoryTest.objects.create(testName=testName,testBodySite=testBodySite,testUse=testUse,testDescription=testDescription, testSpecimen=testSpecimen)
                prescription = Prescription.objects.get(pk=prescriptionId)
                labTestData = LabTestPrescriptionMap.objects.create(laboratoryTestId=laboratoryTestData, prescriptionId=prescription)
            # message='Test Added Successfully!'
            return render(request, 'labTest.html',{'prescriptionId':prescriptionId, 'success':"Test Added Successfully!"})
        else:
            return render(request, 'labTest.html',{'prescriptionId':prescriptionId})
        
    except:
        return render(request, 'labTest.html',{'prescriptionId':prescriptionId,'message':"Something Went Wrong!"})
@doctordata_middleware      
def diagnosis(request, patientId):
    try:
        if request.session['role']!= "Doctor":
            return render(request, 'index.html', {'messages': "You Are Not Authenticated"})
        patient = Patient.objects.filter(id=patientId).first()
        if request.method == 'POST':
            diagnosisName = request.POST.get('diagnosisName',None)
            diagnosisBodySite = request.POST.get('diagnosisBodySite',None)
            if request.POST['dateOfOnset'] == '':

home/views.py
from django.shortcuts import redirect, render,HttpResponse
# from healthcare.models import Patient


# Create your views here.
def homePage(request):
    try:
        return render(request, 'home.html', {})
    except Exception as e:
        print(e)
        return HttpResponse("<h1>something went wrong!!!</h1>")    
def aboutUs(request):
    try:
        return render(request, 'about.html', {})
    except Exception as e:
        print(e)
        return HttpResponse("<h1>something went wrong!!!</h1>")       
def registrationNo(request):
    try:
        return render(request, 'registrationNo.html', {})
    except Exception as e:
        print(e)
        return HttpResponse("<h1>something went wrong!!!</h1>")        
def registrationNoSubmit(request):
    try:
        registrationNumber = request.POST['registerId']
        patient = Patient.objects.filter(registrationNumber=registrationNumber)
        if(patient.exists()):
            patientId=patient.first().id
            return redirect('patientDiagnosis',patientId)
        else:
            return HttpResponse("<h1>No records found!!</h1>")     
    except Exception as e:
        print(e)
        return HttpResponse("<h1>something went wrong!!!</h1>")        
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Home</title>{% endblock %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     
    <style>
        #loginButton{
            background-color: #2f92ad;
            border-color: #2f92ad;
        }
        #navbar-custom{
          background-color: #fbfdfd;
          
        }
        #navBar a{
          transition: transform .2s; /* Animation */
        }

        #navBar a:hover{
          transform: scale(1.2); 
        }

        #page-footer{
            position: relative;
            display: block;
            padding-top: 80px;
            padding-bottom: 17px;
            background-color: #2f92ad;
            color: #fff;
            font-size: 18px;
            
           
        }
        #page-footer a{
          text-decoration: none;
          background-color: none;
          transition: transform .2s; /* Animation */
          
        }
        #page-footer a:hover{
          transform: scale(1.2); 
        }
        
        .footer-menu a{
            display: inline-block;
            padding-top: 6px;
            padding-bottom: 6px;
            color: white;
            transition: all .2s ease;
        }
       
        #page-footer ul{
          list-style: none;
        }
        
       
        
        
       
    </style>
</head>
<body>
    
    <header>
      <div id="navBar">
        <nav class="navbar navbar-expand-lg navbar-light" id="navbar-custom">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <!-- <a class="navbar-brand " href="#" style="font-size: 22px;"><span style="color: #2f92ad;"><i class='fas fa-heartbeat fa-1x'></i>Medi </span>Cal</a> -->
            <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 22px;">
              <span style="color: #2f92ad;"><i class='fas fa-heartbeat fa-1x'></i>Medi </span>Cal
          </a>
          
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03" style="margin-right: 0%;">
              <ul class="navbar-nav ms-auto mb-2 mb-lg-1">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/" style="font-size: 20px; padding-top:10px;">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="/aboutUs" style="font-size: 20px; padding-top:10px;">About Us</a>
                </li>
                {% if user.is_authenticated %}
    {% if user.user_type == 'admin' %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'register' %}" style="font-size: 20px; padding-top:10px;">Register</a>
        </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'doctor' %}" style="font-size: 20px; padding-top:10px;">Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'logout' %}">
            <button type="button" class="btn btn-primary btn-sm-2" id="loginButton">Logout</button>
        </a>
    </li>
{% else %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'login' %}">
                        <button type="button" class="btn btn-primary btn-sm-2" id="loginButton">Login</button>
                    </a>
                </li>
            {% endif %}
            
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    {% block content %} {% endblock %}
    <footer class="page-footer" id="page-footer">
        <div class="container">
          <div class="row px-md-3">
            <div class="col-sm-6 col-lg-3 py-3">
              
              <ul class="footer-menu" id="footer-menu">
                <h3>Company</h3>
                <li><a href="/aboutUs">About Us</a></li>
                <li><a href="#">Career</a></li>
                <li><a href="#">Editorial Team</a></li>
                <li><a href="#">Protection</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
              <ul class="footer-menu">
                <h3>More</h3>
                <li><a href="#">Terms & Condition</a></li>
                <li><a href="#">Privacy</a></li>
                <li><a href="#">Advertise</a></li>
                <li><a href="#">Join as Doctors</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
             <ul class="footer-menu" style="text-decoration: none;">
                <h3>Our partner</h3>
                <li><a href="#">One-Fitness</a></li>
                <li><a href="#">One-Drugs</a></li>
                <li><a href="#">One-Live</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-lg-3 py-3">
              <h3>Contact</h3>
              <p class="footer-link mt-3">Kathmandu, Nepal</p>
              <p>+977-981-111-1110</p>
              <p>medical@health.net</p>
    
              <div class="social mt-2 mb-3 socialCustom">
                 <h5>Social Media
                  <i class="fa fa-facebook-official fa-lg zoomOut"></i>
                  <i class="fa fa-instagram fa-lg zoomOut"></i>
                  <i class="fa fa-twitter fa-lg zoomOut"></i> 
                  <i class="fa fa-linkedin-square fa-lg zoomOut"></i>
                 </h5>
                  
                 
            </div>
          </div>
    
          <hr>
          <p id="copyright" style="text-align: center;">Copyright &copy; 2024 MediCal . All right reserved</p>
        </div>
        
    
</body>
</html>

templates/ragister.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 <style>
 @import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');

* {
	box-sizing: border-box;
}

body {
	background: #f6f5f7;
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	font-family: 'Montserrat', sans-serif;
	height: 100vh;
	margin: -20px 0 50px;
}

h1 {
	font-weight: bold;
	margin: 0;
}

h2 {
	text-align: center;
}

p {
	font-size: 14px;
	font-weight: 100;
	line-height: 20px;
	letter-spacing: 0.5px;
	margin: 20px 0 30px;
}

span {
	font-size: 12px;
}

a {
	color: #333;
	font-size: 14px;
	text-decoration: none;
	margin: 15px 0;
}

button {
	border-radius: 20px;
	border: 1px solid #2f92ad;
	background-color: #2f92ad;
	color: #FFFFFF;
	font-size: 12px;
	font-weight: bold;
	padding: 12px 45px;
	letter-spacing: 1px;
	text-transform: uppercase;
	transition: transform 80ms ease-in;
}

button:active {
	transform: scale(0.95);
}

button:focus {
	outline: none;
}

button.ghost {
	background-color: transparent;
	border-color: #FFFFFF;
}

form {
	background-color: #FFFFFF;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 50px;
	height: 100%;
	text-align: center;
}

input {
	background-color: #eee;
	border: none;
	padding: 12px 15px;
	margin: 8px 0;
	width: 100%;
}

.container {
	background-color: #fff;
	border-radius: 10px;
  	box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
			0 10px 10px rgba(0,0,0,0.22);
	position: relative;
	overflow: hidden;
	width: 768px;
	max-width: 100%;
	min-height: 480px;
}

.form-container {
	position: absolute;
	top: 0;
	height: 100%;
	transition: all 0.6s ease-in-out;
}

.sign-in-container {
	left: 0;
	width: 50%;
	z-index: 2;
}

.container.right-panel-active .sign-in-container {
	transform: translateX(100%);
}

.sign-up-container {
	left: 0;
	width: 50%;
	opacity: 0;
	z-index: 1;
}

.container.right-panel-active .sign-up-container {
	transform: translateX(100%);
	opacity: 1;
	z-index: 5;
	animation: show 0.6s;
}

@keyframes show {
	0%, 49.99% {
		opacity: 0;
		z-index: 1;
	}
	
	50%, 100% {
		opacity: 1;
		z-index: 5;
	}
}

.overlay-container {
	position: absolute;
	top: 0;
	left: 50%;
	width: 50%;
	height: 100%;
	overflow: hidden;
	transition: transform 0.6s ease-in-out;
	z-index: 100;
}

.container.right-panel-active .overlay-container{
	transform: translateX(-100%);
}

.overlay {
	background: #2f92ad;
	background: -webkit-linear-gradient(to right, #2f92ad, #65e4ca);
	background: linear-gradient(to right, #2f92ad, #65e4ca);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: 0 0;
	color: #FFFFFF;
	position: relative;
	left: -100%;
	height: 100%;
	width: 200%;
  	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.container.right-panel-active .overlay {
  	transform: translateX(50%);
}

.overlay-panel {
	position: absolute;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 40px;
	text-align: center;
	top: 0;
	height: 100%;
	width: 50%;
	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.overlay-left {
	transform: translateX(-20%);
}

.container.right-panel-active .overlay-left {
	transform: translateX(0);
}

.overlay-right {
	right: 0;
	transform: translateX(0);
}

.container.right-panel-active .overlay-right {
	transform: translateX(20%);
}

.social-container {
	margin: 20px 0;
}

.social-container a {
	border: 1px solid #DDDDDD;
	border-radius: 50%;
	display: inline-flex;
	justify-content: center;
	align-items: center;
	margin: 0 5px;
	height: 40px;
	width: 40px;
}

footer {
    background-color: #222;
    color: #fff;
    font-size: 14px;
    bottom: 0;
    position: fixed;
    left: 0;
    right: 0;
    text-align: center;
    z-index: 999;
}

footer p {
    margin: 10px 0;
}

footer i {
    color: #2f92ad;
}

footer a {
    color: #3c97bf;
    text-decoration: none;
}

 </style>   
</head>
<body>

  <div class="container" id="container">

    <div class="form-container sign-in-container">
        <form method="post">
			{% csrf_token %}
			
			{{ form.username }}
		
			
			{{ form.full_name }}
		
			
			{{ form.email }}
		
			
			
			{{ form.phone }}
		
	
			{{ form.password }}
		
			<input type="hidden" id="id_user_type" name="user_type" value="admin">
        
			<button type="submit">Register</button>
      </form>
    </div>
    <div class="overlay-container">
      <div class="overlay">
        <div class="overlay-panel overlay-left">
          <h1>Welcome Back!</h1>
          <p>To keep connected with us please login with your personal info</p>
          <button class="ghost" id="signIn">Register</button>
        </div>
        <div class="overlay-panel overlay-right">
          <h1>Welcome</h1>
		  <h3 style="color: white">{{message}}</h3>
        </div>
      </div>
    </div>
  </div>     
</body>
<script>
var password = document.getElementById("password")
var confirm_password = document.getElementById("confirm_password");
  
  function validatePassword(){
	if(password.value != confirm_password.value) {
	  confirm_password.setCustomValidity("Passwords Don't Match");
	} else {
	  confirm_password.setCustomValidity('');
	}
  }
  
  password.onchange = validatePassword;
  confirm_password.onkeyup = validatePassword;

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>